/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isBestseller' : IDL.Bool,
  'price' : IDL.Int32,
});

export const idlService = IDL.Service({
  'createProduct' : IDL.Func([IDL.Text, Product], [], []),
  'deleteProduct' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
  'updateProductDescription' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'verifyPasskey' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isBestseller' : IDL.Bool,
    'price' : IDL.Int32,
  });
  
  return IDL.Service({
    'createProduct' : IDL.Func([IDL.Text, Product], [], []),
    'deleteProduct' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
    'updateProductDescription' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'verifyPasskey' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };